services:
  - type: web
    name: ai-content-generator
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn config.wsgi:application --chdir backend"
    envVars:
      - key: OPENAI_API_KEY
        sync: false

